# Enterprise-grade local development environment
version: '3.8'

services:
  # PostgreSQL with pgvector extension
  postgres:
    image: pgvector/pgvector:pg16
    container_name: querygenie-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: querygenie
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d querygenie"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - querygenie-network

  # Redis for caching and sessions
  redis:
    image: redis:7.2-alpine
    container_name: querygenie-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass redis123
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - querygenie-network

  # Drizzle Studio for database GUI (optional)
  drizzle-studio:
    image: node:20-alpine
    container_name: querygenie-drizzle-studio
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install -g drizzle-kit && drizzle-kit studio --host 0.0.0.0 --port 4983"
    ports:
      - "4983:4983"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=development
    networks:
      - querygenie-network
    profiles:
      - tools

  # Mailhog for email testing (optional)
  mailhog:
    image: mailhog/mailhog:latest
    container_name: querygenie-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    networks:
      - querygenie-network
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  querygenie-network:
    driver: bridge